"""initial schema

Revision ID: 93d193e7908e
Revises: 
Create Date: 2026-07-29 22:55:11.274100
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.crypto  # tipo customizado EncryptedStr


# revision identifiers, used by Alembic.
revision: str = '93d193e7908e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=180), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('detail', sa.String(length=1000), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity'), ['entity'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('portfolio', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pacing', sa.Float(), nullable=False),
    sa.Column('agents_online', sa.Integer(), nullable=False),
    sa.Column('mailing_total', sa.Integer(), nullable=False),
    sa.Column('mailing_worked', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_portfolio'), ['portfolio'], unique=False)

    op.create_table('debtors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document', app.core.crypto.EncryptedStr(length=255), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('person_type', sa.String(length=2), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('phone_alt', sa.String(length=30), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('zip_code', sa.String(length=9), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('neighborhood', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('contact_status', sa.String(length=20), nullable=False),
    sa.Column('is_anonymized', sa.Boolean(), nullable=False),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debtors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debtors_document_hash'), ['document_hash'], unique=False)

    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('squad', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_features_status'), ['status'], unique=False)

    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_month', sa.String(length=7), nullable=False),
    sa.Column('portfolio', sa.String(length=20), nullable=False),
    sa.Column('expected_recovery', sa.Float(), nullable=False),
    sa.Column('expected_volume', sa.Integer(), nullable=False),
    sa.Column('assumptions', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecasts_portfolio'), ['portfolio'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_reference_month'), ['reference_month'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_month', sa.String(length=7), nullable=False),
    sa.Column('portfolio', sa.String(length=20), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('achieved_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_portfolio'), ['portfolio'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_reference_month'), ['reference_month'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('service', sa.String(length=80), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)

    op.create_table('pacing_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('idle_pct', sa.Float(), nullable=False),
    sa.Column('abandon_pct', sa.Float(), nullable=False),
    sa.Column('calls_made', sa.Integer(), nullable=False),
    sa.Column('contacts', sa.Integer(), nullable=False),
    sa.Column('promises', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pacing_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pacing_snapshots_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('system_health_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('cpu_pct', sa.Float(), nullable=False),
    sa.Column('mem_pct', sa.Float(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_health_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_health_checks_service'), ['service'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('accepted_terms_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debtor_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('legal_basis', sa.String(length=40), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_debtor_id'), ['debtor_id'], unique=False)

    op.create_table('data_subject_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debtor_id', sa.Integer(), nullable=True),
    sa.Column('requester_document', sa.String(length=20), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('handled_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_subject_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_subject_requests_debtor_id'), ['debtor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_subject_requests_requester_document'), ['requester_document'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_subject_requests_status'), ['status'], unique=False)

    op.create_table('debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debtor_id', sa.Integer(), nullable=False),
    sa.Column('contract_ref', sa.String(length=60), nullable=False),
    sa.Column('portfolio', sa.String(length=20), nullable=False),
    sa.Column('creditor', sa.String(length=160), nullable=False),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debts_contract_ref'), ['contract_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_debts_debtor_id'), ['debtor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debts_portfolio'), ['portfolio'], unique=False)
        batch_op.create_index(batch_op.f('ix_debts_status'), ['status'], unique=False)

    op.create_table('sector_accesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=40), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sector', name='uq_user_sector')
    )
    with op.batch_alter_table('sector_accesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sector_accesses_user_id'), ['user_id'], unique=False)

    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debtor_id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('promise_amount', sa.Float(), nullable=True),
    sa.Column('promise_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_debt_id'), ['debt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_debtor_id'), ['debtor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_result'), ['result'], unique=False)

    op.create_table('payment_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('installment_amount', sa.Float(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_agreements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_agreements_debt_id'), ['debt_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_debt_id'), ['debt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_debt_id'))

    op.drop_table('payments')
    with op.batch_alter_table('payment_agreements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_agreements_debt_id'))

    op.drop_table('payment_agreements')
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_result'))
        batch_op.drop_index(batch_op.f('ix_interactions_debtor_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_debt_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_created_at'))

    op.drop_table('interactions')
    with op.batch_alter_table('sector_accesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sector_accesses_user_id'))

    op.drop_table('sector_accesses')
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debts_status'))
        batch_op.drop_index(batch_op.f('ix_debts_portfolio'))
        batch_op.drop_index(batch_op.f('ix_debts_debtor_id'))
        batch_op.drop_index(batch_op.f('ix_debts_contract_ref'))

    op.drop_table('debts')
    with op.batch_alter_table('data_subject_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_subject_requests_status'))
        batch_op.drop_index(batch_op.f('ix_data_subject_requests_requester_document'))
        batch_op.drop_index(batch_op.f('ix_data_subject_requests_debtor_id'))

    op.drop_table('data_subject_requests')
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_records_debtor_id'))

    op.drop_table('consent_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('system_health_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_health_checks_service'))

    op.drop_table('system_health_checks')
    with op.batch_alter_table('pacing_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pacing_snapshots_campaign_id'))

    op.drop_table('pacing_snapshots')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))

    op.drop_table('incidents')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_reference_month'))
        batch_op.drop_index(batch_op.f('ix_goals_portfolio'))

    op.drop_table('goals')
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecasts_reference_month'))
        batch_op.drop_index(batch_op.f('ix_forecasts_portfolio'))

    op.drop_table('forecasts')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_status'))

    op.drop_table('features')
    op.drop_table('deployments')
    with op.batch_alter_table('debtors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debtors_document_hash'))

    op.drop_table('debtors')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_portfolio'))

    op.drop_table('campaigns')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
