"""add dsr identity verification

Revision ID: e1cb094f7556
Revises: ead0c5c39ae3
Create Date: 2026-07-29 23:19:58.928918
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1cb094f7556'
down_revision: Union[str, None] = 'ead0c5c39ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_subject_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester_email', sa.String(length=180), nullable=True))
        # server_default garante segurança ao adicionar coluna NOT NULL em
        # tabelas que já possuam linhas (deployments existentes).
        batch_op.add_column(
            sa.Column(
                'identity_verified',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_subject_requests', schema=None) as batch_op:
        batch_op.drop_column('identity_verified')
        batch_op.drop_column('requester_email')

    # ### end Alembic commands ###
